import { Inter } from "next/font/google";
import "./globals.css";
import NavbarPage from "@/components/ui/navbar";
import PopUpOpener from "@/components/popup/popup";
import PopUpOpenerVideo from "@/components/popup/popupVideo";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavbarPage/>
        {children}
        <PopUpOpener/>
        <PopUpOpenerVideo/>
        
        </body>
    </html>
  );
}
